### ISSUE TITLE
Support for themes

### ISSUE THREAD

**Issue by mastoj** [dbrattli/Felizia#3]
I noticed the comment, so I thought it might be good with an issue so it can be discussed.

**Comment by mastoj** [comment]
Question:

Why is it that you have the layouts as files you include rather than a shared project? I imagine have it as a project that was shared would make it easier to add themes as nuget packages maybe? All that is needed should then maybe just be some simple "registration" of a theme.

**Comment by dbrattli** [comment]
I added the comment so I could get feedback like this. This is a great suggestion. Let's discuss how we can make this work with e.g https://gohugo.io/templates/lookup-order/

**Comment by dbrattli** [comment]
Have started to separate the theme into a separate project. It's a bit of work as Felizia now must be a separate library from the application itself, but this is something we want. Will move more files from the app over to the library.

The theme is still hard-coded so that is something we need to look into. In Hugo you select the theme in the config by setting `theme = "name"`. We could use reflection here to select a theme that has been linked into the project. Any ideas here of what we can do?

**Comment by dbrattli** [comment]
Current status: https://github.com/dbrattli/Felizia/pull/4
